### ISSUE TITLE
Got crash issue from Fabric.

### ISSUE THREAD

**Issue by developeraminul** [huynguyencong/NHNetworkTime#30] opened 2018-10-11 09:39 UTC
Platform: ios
 Bundle Identifier: 
 Issue #: 980
 Issue ID: 5b859cb16007d59fcd1352c2
 Session ID: 88f95cab8b4c4d3da433ccfb2a5ddb41_DNE_0_v2
 Date: 2018-10-09T10:33:00Z
 OS Version: 12.0.0 (16A366)
 Device: iPhone 6
 RAM Free: 1.5%
 Disk Free: 41.3%

#0. Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x182f84d68 objc_msgSend + 8
1  NHNetworkTime                  0x1025afeec -[NHNetworkClock finishAssociations] + 244
2  NHNetworkTime                  0x1025af334 -[NHNetworkClock reset] + 48
3  NHNetworkTime                  0x1025affc8 -[NHNetworkClock synchronize] + 32
4  Foundation                     0x184744fdc -[__NSObserver _doit:] + 316
5  CoreFoundation                 0x183d0cd14

**Comment by huynguyencong** [comment] 2018-11-06 03:46
Could you please provide more detail for me? For example, how you use this lib in your project.

**Comment by developeraminul** [comment] 2018-11-06 12:23
I use cocoapod to configure this lib in our project. From the Podfile.lock file I found that NHNetworkTime version is 1.7. We found several crash in this lib but frequency is not so high (10-20).

**Comment by huynguyencong** [comment] 2018-11-09 04:00
I can't reproduce the crash. Let me do some investigate. Thanks for your feedback.

**Comment by developeraminul** [comment] 2018-11-09 10:06
Sure .. you can investigate more and this is a sometimes issue. 
One more request  please give a new version release for cocoapod. (Becuase i found that you gave some new changes which are not included in cocoapod's version).

**Comment by huynguyencong** [comment] 2021-05-24 05:32
Sorry, long time and I couldn't reproduce, so I close this issue.

**Closed as completed by huynguyencong** 2021-05-24 05:32 UTC
