### ISSUE TITLE
File Descriptor leaks

### ISSUE THREAD

**Issue by dlavlinskyi** [huynguyencong/NHNetworkTime#20] opened 2016-11-29 11:43 UTC
1. Put this code `[[NHNetworkClock sharedNetworkClock] synchronize];`
into `applicationDidBecomeActive`
2. print used File Descriptors using `lsof` function from the following stackoverflow post http://stackoverflow.com/a/8153026
3. Use lsof in `applicationDidBecomeActive` and `applicationWillResignActive`
4. Make app active/inactive 10+ times.
Result: File Descriptors amount will grow up like crazy. Finally you will get 'Too many open files' error and app will not work correctly or crash.

**Comment by mmahkamov** [comment] 2017-05-31 10:52
The leak is caused by NHNetAssociation, which is never deallocated due to strong references to it. I'm almost done with the fix, will post it.

**Comment by dlavlinskyi** [comment] 2017-05-31 10:56
Thank you very much

**Comment by mmahkamov** [comment] 2017-05-31 11:36
I have created a pull request with the fix:
https://github.com/huynguyencong/NHNetworkTime/pull/24

Meanwhile you can use the fixed code from my fork directly until the pull request is accepted:
https://github.com/mmahkamov/NHNetworkTime/tree/net_association_leak_fix

If you're using Cocoapods:

`pod 'NHNetworkTime', :git => 'https://github.com/mmahkamov/NHNetworkTime.git', :branch => 'net_association_leak_fix'`

**Comment by mmahkamov** [comment] 2017-05-31 12:53
I found more leaks, this time I see a lot of CocoaAsyncSocket objects which are not being freed. I

**Comment by mmahkamov** [comment] 2017-06-01 05:58
It's done now. I pushed the latest commit to my fork. Once the pull request is accepted you'll be able to get the fix. Or you can get it from my fork for now as I described above.

**Comment by huynguyencong** [comment] 2018-04-18 04:36
Merged it. Thank you guys

**Closed as completed by huynguyencong** 2018-04-18 04:36 UTC
